openapi: '3.0.2'
info:
  title: Delivery System
  version: '1.0'

servers:
  - url: http://localhost:3000
    description: Internal staging server for testing

paths:
  /restaurants:
    get:
      tags:
        - Restaurants
      description: List all restaurants.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
        - in: query
          name: cursor
          schema:
            $ref: '#/components/schemas/ObjectID'
          description: Restaurant ID used as a keyset for bidirectional pagination (next and previous pages)
      responses:
        "200":
          description: A JSON of all Restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restaurant"
        default:
          $ref: "#/components/responses/Error"
    post:
      tags:
        - Restaurants
      description: Create a restaurant.
      requestBody:
        description: Restaurant details
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - name
                - address
              properties:
                name:
                  type: string
                address:
                  type: string
            example:
              name: Burguer House
              address: Rua XPTO, 123
      responses:
        "201":
          description: A JSON of created Restaurant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
        default:
          $ref: "#/components/responses/Error"
  
  /restaurants/{id}/categories:
    get:
      tags:
        - Categories
      description: List all the categories of a restaurant sorted by index.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the restaurant.
          schema:
            $ref: '#/components/schemas/ObjectID'
      responses:
        "200":
          description: A JSON of all Categories sorted by index
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        default:
          $ref: "#/components/responses/Error"
    post:
      tags:
        - Categories
      description: Create a category for a restaurant.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the restaurant.
          schema:
            $ref: '#/components/schemas/ObjectID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - name
                - index
              properties:
                name:
                  type: string
                index:
                  type: number
      responses:
        '201':
          description: A JSON of created Category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        default:
          $ref: "#/components/responses/Error"
  
  /categories/{id}/products:
    get:
      tags:
        - Products
      description: List all the products of a category.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the category.
          schema:
            $ref: '#/components/schemas/ObjectID'
      responses:
        "200":
          description: A JSON of all Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        default:
          $ref: "#/components/responses/Error"
    post:
      tags:
        - Products
      description: Create a product of a category.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the category.
          schema:
            $ref: '#/components/schemas/ObjectID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - name
                - price
                - description
                - isAvailable
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
                isAvailable:
                  type: boolean
      responses:
        '201':
          description: A JSON of created Product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        default:
          $ref: "#/components/responses/Error"

  /orders:
    post:
      tags:
        - Orders
      description: Create a new order.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - restaurantId
                - items
                - priceTotal
              properties:
                restaurantId:
                  $ref: '#/components/schemas/ObjectID'
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/OrderProduct'
                priceTotal:
                  type: number
      responses:
        '201':
          description: A JSON of created Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        default:
          $ref: "#/components/responses/Error"
  
  /restaurants/{id}/orders:
    get:
      tags:
        - Orders
      description: List all the orders of a restaurant.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the restaurant.
          schema:
            $ref: '#/components/schemas/ObjectID'
      responses:
        "200":
          description: A JSON of all Orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        default:
          $ref: "#/components/responses/Error"
  
  /orders/{id}/status:
    patch:
      tags:
        - Orders
      description: Updates the status of an order.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the order.
          schema:
            $ref: '#/components/schemas/ObjectID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - status
              properties:
                status:
                  $ref: '#/components/schemas/OrderStatus'
      responses:
        '200':
          description: A JSON of updated Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        default:
          $ref: "#/components/responses/Error"

components:
  responses:
    Error:
      description: Invalid request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    ObjectID:
      type: string
      pattern: '^[0-9a-fA-F]{24}$'

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    Restaurant:
      type: object
      required:
        - _id
        - name
        - address
      properties:
        _id:
          $ref: '#/components/schemas/ObjectID'
        name:
          type: string
        address:
          type: string
    
    Category:
      type: object
      required:
        - _id
        - restaurantId
        - name
        - index
      properties:
        _id:
          $ref: '#/components/schemas/ObjectID'
        restaurantId:
          $ref: '#/components/schemas/ObjectID'
        name:
          type: string
        index:
          type: number

    Product:
      type: object
      required:
        - _id
        - categoryId
        - restaurantId
        - name
        - price
        - description
        - isAvailable
      properties:
        _id:
          $ref: '#/components/schemas/ObjectID'
        categoryId:
          $ref: '#/components/schemas/ObjectID'
        restaurantId:
          $ref: '#/components/schemas/ObjectID'
        name:
          type: string
        price:
          type: number
        description:
          type: string
        isAvailable:
          type: boolean

    OrderProduct:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          $ref: '#/components/schemas/ObjectID'
        quantity:
          type: number
    
    OrderStatus:
      type: string
      enum:
        - PENDING
        - PREPARING
        - OUT_FOR_DELIVERY
        - COMPLETED
        - CANCELED

    Order:
      type: object
      required:
        - _id
        - restaurantId
        - items
        - priceTotal
        - status
      properties:
        _id:
          $ref: '#/components/schemas/ObjectID'
        restaurantId:
          $ref: '#/components/schemas/ObjectID'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderProduct'
        priceTotal:
          type: number
        status:
          $ref: '#/components/schemas/OrderStatus'